<?php
/**
 * Created by
 * User: GuoZhaoXuan
 * Date: 2021/8/13
 * Time: 16:15
 */

namespace Vartruexuan\EasyOutApi\Test\api;


use Vartruexuan\EasyOutApi\OutApi\OutApiAbstract;
use GuzzleHttp\Psr7\Response;
use GuzzleHttp\Psr7\Request;

class TestApi extends OutApiAbstract
{

    protected $defaultConfig = [
        'baseUrl' => 'https://postman-echo.com', // domain
        'isMock' => false,
        'routes' => [
            'sendApi' => [
                'method' => 'GET',
                'route' => '/get',
            ],
            'sendMock' => [
                'method' => 'POST',
                'route' => '/sendMock',
            ],
            'sendRouteParam' => [
                'method' => 'POST',
                'route' => '/sendRouteParam/{id}',
            ],
            'sendRetry' => [],
        ],
    ];


    public function sendApi()
    {
        return $this->request('sendApi');
    }


    /**
     * @return array|mixed|Response
     * @author:郭昭璇
     */
    public function sendMock()
    {
        return $this->request('sendMock');
    }

    /**
     * @param  \GuzzleHttp\Psr7\Request  $request
     * @param  array  $options
     *
     * @return mixed|void
     * @see https://guzzle-cn.readthedocs.io/zh_CN/latest/request-options.html
     */
    function beforeAction(Request $request, &$options = [])
    {
        // $options['proxy']='http://127.0.0.1:8889';

        // 模拟签名
        $secret='123';
        $options['headers']=['token'=>md5($request->getUri().$secret)];

        // TODO: Implement beforeAction() method.
    }

    function isRetry(?Response $response, $retries = 0): bool
    {
        $result=$response->getBody();
        $result=json_decode($result,true);
        if(!$result || !isset($result['code'])||$result['code']!=200){
            return  true;
        }
        return false;
        // TODO: Implement isRetry() method.
    }

    /**
     * @param $response
     *
     * @return array|mixed|Response
     */
    function dataFormat($response)
    {
        return parent::dataFormat($response); // TODO: Change the autogenerated stub
    }

}