<?php
/**
 * Created by
 * User: GuoZhaoXuan
 * Date: 2021/8/2
 * Time: 11:03
 */

namespace Vartruexuan\EasyOutApi\OutApi\Client;

use Vartruexuan\EasyOutApi\Kernel\BaseClient;
use Psr\Http\Message\RequestInterface;

class OutApiClient extends BaseClient
{

 public function request(string $url, string $method = 'GET', array $options = [], $returnRaw = false)
 {
     // TODO: Change the autogenerated stub
     try{
         return parent::request($url, $method, $options, $returnRaw);
     }catch (\Throwable $e){

     }
 }

    protected function registerHttpMiddlewares()
    {
        parent::registerHttpMiddlewares(); // TODO: Change the autogenerated stub

        $this->pushMiddleware($this->beforeActionMiddleware());
    }

    /**
     * before Action request
     *
     * @return \Closure
     */
    private function beforeActionMiddleware()
    {
        return function (callable $handler)  {
            return function (RequestInterface $request, array $options) use ($handler) {
                $this->app->beforeAction($request,$options);
                return $handler($request, $options);
            };
        };
    }
}